-- 09_seed_playbooks.sql
-- 12 starter playbooks ported from the old Base44 seedPlaybooks function.
-- Covers cold outreach (5 steps), 5 objection handlers, 1 closing framework,
-- 1 discovery checklist. Idempotent via on conflict (code) do nothing.

insert into public.playbooks(code, title, category, visible_to_roles, content_type, short_description, full_content, related_objection, is_favorite_eligible) values
('cold_call_open', '5-Step Cold Call — Open', 'cold_outreach',
  array['field_agent','cpc','admin'], 'script',
  'Open with curiosity, not a pitch',
  E'Step 1 — OPEN with curiosity, not a pitch\n\n"Hi, is this the owner? I''m [Name] from Marketing iO — quick question: when someone in [City] searches for [their type of business] on Google, do you come up?"',
  null, true),
('cold_call_qualify', '5-Step Cold Call — Qualify', 'cold_outreach',
  array['field_agent','cpc','admin'], 'script',
  'Qualify the pain after opening',
  E'Step 2 — QUALIFY the pain\n\nLet them respond. If they say no or aren''t sure:\n\n"That''s exactly what we help with — most businesses in Limpopo are invisible online and don''t even know it."',
  null, true),
('cold_call_present', '5-Step Cold Call — Present Value', 'cold_outreach',
  array['field_agent','cpc','admin'], 'script',
  'Present value, not features',
  E'Step 3 — PRESENT the value (not features)\n\n"We set up your full online presence — website, social media, ads — and we do it all for one low monthly fee."',
  null, true),
('cold_call_handle', '5-Step Cold Call — Handle Objections', 'cold_outreach',
  array['field_agent','cpc','admin'], 'script',
  'Feel/Felt/Found framework',
  E'Step 4 — HANDLE objections with FEEL/FELT/FOUND\n\n"I understand — a lot of our clients felt exactly the same way before they started."',
  null, true),
('cold_call_close', '5-Step Cold Call — Close for Meeting', 'cold_outreach',
  array['field_agent','cpc','admin'], 'script',
  'Close for the meeting, not the sale',
  E'Step 5 — CLOSE for the MEETING, not the sale\n\n"Are you available Tuesday or Wednesday for a 20-minute visit?"',
  null, true),
('obj_no_money', 'Objection: No money for marketing', 'objection_handler',
  array['field_agent','cpc','admin'], 'script',
  'Handle ''I don''t have budget'' objection',
  E'That''s exactly why you need it. Businesses invisible online lose customers every day.\n\nOur starter package is less than R600/month — less than a tank of petrol.\n\n**Follow-up:** "If it brings you just 2 extra customers a month, does it pay for itself?"',
  'I don''t have money for marketing', true),
('obj_facebook', 'Objection: Already on Facebook', 'objection_handler',
  array['field_agent','cpc','admin'], 'script',
  'Handle ''I''m already on Facebook'' objection',
  E'Having a Facebook page is a start — but is it generating leads?\n\nWe manage the page, run paid ads, and track every result.\n\n**Follow-up:** "How many leads came from your page last month — do you know?"',
  'I''m already on Facebook', true),
('obj_think_about', 'Objection: I''ll think about it', 'objection_handler',
  array['field_agent','cpc','admin'], 'script',
  'Handle stalling / thinking about it',
  E'Of course — what specific concerns can I address now?\n\nMost clients say the biggest concern was results — let me show you what we did for a similar business.\n\n**Follow-up:** "What would need to be true for you to feel confident moving forward?"',
  'I''ll think about it', true),
('obj_tried_before', 'Objection: Tried marketing before', 'objection_handler',
  array['field_agent','cpc','admin'], 'script',
  'Handle bad past experiences',
  E'That''s common with agencies that disappear. We''re based here in Polokwane — you can call me, visit me, or WhatsApp me any time.\n\n**Follow-up:** "What specifically didn''t work? Help me understand what you tried so I can show you exactly what we''d do differently."',
  'I tried marketing before and it didn''t work', true),
('obj_diy', 'Objection: We''ll do it ourselves', 'objection_handler',
  array['field_agent','cpc','admin'], 'script',
  'Handle DIY marketing objection',
  E'Absolutely — and if you find you don''t have time to stay consistent, we''re here.\n\nCan I at least show you a free audit of your current online presence?\n\n**Follow-up:** "How many hours a week do you currently spend on marketing?"',
  'We''ll do it ourselves', true),
('close_trial', 'Trial Close Framework', 'closing',
  array['field_agent','cpc','admin'], 'framework',
  'Assume interest, choose between packages',
  E'**Trial Close:**\n"Based on what we''ve discussed, does Ignite or Accelerate make more sense for [business_name]?"\n\n**Assumed Close:**\n"Let me get the contract started — what''s your business registration number?"\n\n**Urgency Close:**\n"We have 2 setup slots left this month. If we get the deposit by Friday, you''re live by next month-end."\n\n**Risk-Reversal Close:**\n"If you''re not getting results in month 1, we''ll keep working at no extra cost until you are."',
  null, true),
('discovery_7_questions', '7 Discovery Questions', 'discovery',
  array['field_agent','cpc','admin'], 'checklist',
  'The 7 questions to always ask on a discovery visit',
  E'**Ask these 7 questions on every discovery visit:**\n\n1. How long has [business_name] been operating?\n2. Where do most of your customers come from today?\n3. What''s the biggest challenge in growing [business_name] right now?\n4. How are people finding you online today — are they?\n5. What does success look like for the next 6 months?\n6. What''s your monthly marketing budget right now?\n7. If we got you 5 quality leads a week starting next month, what would that mean for the business?',
  null, true)
on conflict (code) do nothing;
