-- Migration 100: schema + read/write RPCs for Directive 21.
--
-- Schema additions
--   contracts.id_verified                (bool, default false)
--   contracts.banking_captured           (bool, default false)
--   contracts.contract_name              (text)
--   clients.security_question_1 / _2     (text)
--   clients.security_answer_1_hash / _2_hash  (bcrypt via pgcrypto's crypt())
--   clients.trading_name                 (text)
--   clients.registration_number          (text)
--   clients.vat_number                   (text)
--   clients.employee_count               (int)
--   clients.years_in_business            (int)
--   clients.twitter_handle               (text)
--
-- RPC surface for the client portal
--   get_client_dashboard() — now returns a deals_list so the Products
--     page can render owned services in an "Active" grey-out state.
--   get_my_contracts()     — now returns id_verified, banking_captured,
--     popia_signed (mio_signed_at already there from migration 98) and
--     add_on_name so the verification scanner + outstanding list can
--     render an accurate readout.
--   get_my_profile()       — expands to industry, brand, social,
--     business info + security_questions_set flag (never the answers).
--   client_self_update()   — whitelist expanded to allow the new business
--     and Twitter fields via the same JSON-patch RPC used everywhere else.
--   update_my_security_questions(q1, a1, q2, a2) — stores question text
--     plain; answers as bcrypt hashes (crypt + gen_salt('bf', 8)). Never
--     reads the answers back — a support-time verify function will
--     compare crypt(input, stored_hash) = stored_hash.
--   get_my_billing()       — feeds the three-tab /client/billing page:
--     Overview (monthly retainer, debit day, totals), Payment History
--     (every invoice), Bank Details (masked account, mandate status).

-- (Full body applied via mcp__Supabase__apply_migration; see
-- supabase/migrations history for the canonical form.)
